apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastapi-demo.fullname" . }}
  labels:
    {{- include "fastapi-demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "fastapi-demo.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      name: http
---
{{- if .Values.nodePort.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastapi-demo.fullname" . }}-nodeport
  labels:
    {{- include "fastapi-demo.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    {{- include "fastapi-demo.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.nodePort.port }}
      name: http
{{- end }}
